### ISSUE TITLE
Identify 508 compliance failures within Facilities API Swagger UI

### ISSUE THREAD

**Issue by davidkwartler** [US-EPA-CAMD/easey-ui#138]
- [ ] Identify 508 accessibility compliance failures for the Facilities API using Swagger UI

https://easey-dev.app.cloud.gov/api/facilities/swagger/

**Comment by aprematta** [comment]
[Facilities API Swagger UI Accessibility Report.docx](https://github.com/US-EPA-CAMD/easey-ui/files/5569662/Facilities.API.Swagger.UI.Accessibility.Report.docx)

**Comment by aprematta** [comment]
Adding accessibility report

**Comment by aprematta** [comment]
@jorjacomer @jwhitehead77, accessibility report for the api is attached to the ticket
